ibori:
  framework:
    security:
      jwt:
        secret: default-secret-key-ibori-framework-must-be-changed-in-prod
        accessTokenTtl: 30m
        refreshTokenTtl: 14d
        issuer: modern-mma-platform